module.exports = function (env) {
    return {
            // Railway inputs
            ADMIN_EMAIL: env.ADMIN_EMAIL,
            ADMIN_PASSWORD: env.ADMIN_PASSWORD,
            KEY: env.KEY,
            SECRET: env.SECRET,

            // https://docs.railway.app/guides/public-networking#railway-provided-port
            PORT: env.PORT,

            PUBLIC_URL: `http://0.0.0.0:${env.PORT}`,

            // Database & storage variables for connecting to PostGIS and S3/local storage
            DB_CLIENT: "pg",
            DB_CONNECTION_STRING: env.DB_CONNECTION_STRING,
            STORAGE_LOCATIONS: env.STORAGE_LOCATIONS,
            STORAGE_S3_DRIVER: env.STORAGE_S3_DRIVER,
            STORAGE_S3_KEY: env.STORAGE_S3_KEY,
            STORAGE_S3_SECRET: env.STORAGE_S3_SECRET,
            STORAGE_S3_REGION: env.STORAGE_S3_REGION,
            STORAGE_S3_BUCKET: env.STORAGE_S3_BUCKET,
            STORAGE_S3_ENDPOINT: env.STORAGE_S3_ENDPOINT,
            WEBSOCKETS_ENABLED: env.WEBSOCKETS_ENABLED,
            CORS_ENABLED: env.CORS_ENABLED || true,
            CORS_ORIGIN: env.CORS_ORIGIN || "*",
            CORS_ALLOWED_HEADERS: env.CORS_ALLOWED_HEADERS || "*",
            CORS_EXPOSED_HEADERS: env.CORS_EXPOSED_HEADERS || "*",
            CORS_METHODS: env.CORS_METHODS || "*",
            EXTENSIONS_PATH: env.EXTENSIONS_PATH || "./extensions",
            EMAIL_TEMPLATES_PATH: env.EMAIL_TEMPLATES_PATH || "./templates",
            MIGRATIONS_PATH: env.MIGRATIONS_PATH || "./migrations",
            CACHE_ENABLED: env.CACHE_ENABLED || false,
            CACHE_TTL: env.CACHE_TTL || "5m",
            CACHE_CONTROL_S_MAXAGE: env.CACHE_CONTROL_S_MAXAGE || 0,
            ASSETS_TRANSFORM_MAX_CONCURRENT: env.ASSETS_TRANSFORM_MAX_CONCURRENT || 25,
            ASSETS_TRANSFORM_MAX_OPERATIONS: env.ASSETS_TRANSFORM_MAX_OPERATIONS || 5,
            RATE_LIMITER_ENABLED: env.RATE_LIMITER_ENABLED || false,
            RATE_LIMITER_POINTS: env.RATE_LIMITER_POINTS || 50,
            RATE_LIMITER_DURATION: env.RATE_LIMITER_DURATION || 1,
            RATE_LIMITER_STORE: env.RATE_LIMITER_STORE || "memory",
            ACCESS_TOKEN_TTL: env.ACCESS_TOKEN_TTL || "15m",
            REFRESH_TOKEN_TTL: env.REFRESH_TOKEN_TTL || "7d",
            REFRESH_TOKEN_COOKIE_SECURE: env.REFRESH_TOKEN_COOKIE_SECURE || true,
            REFRESH_TOKEN_COOKIE_SAME_SITE: env.REFRESH_TOKEN_COOKIE_SAME_SITE || "lax",
            SESSION_COOKIE_TTL: env.SESSION_COOKIE_TTL || "1d",
            SESSION_COOKIE_SECURE: env.SESSION_COOKIE_SECURE || true,
            SESSION_COOKIE_SAME_SITE: env.SESSION_COOKIE_SAME_SITE || "lax",
            USER_REGISTER_URL_ALLOW_LIST: env.USER_REGISTER_URL_ALLOW_LIST || "*",
            EMAIL_TRANSPORT: env.EMAIL_TRANSPORT,
            EMAIL_SMTP_HOST: env.EMAIL_SMTP_HOST,
            EMAIL_SMTP_PORT: env.EMAIL_SMTP_PORT,
            EMAIL_SMTP_SECURE: env.EMAIL_SMTP_SECURE,
            EMAIL_SMTP_USER: env.EMAIL_SMTP_USER,
            EMAIL_SMTP_PASSWORD: env.EMAIL_SMTP_PASSWORD,
            EMAIL_FROM: env.EMAIL_FROM,
    };
};
