# Explicitly specify a Directus version to use on Railway
FROM directus/directus:11.10

USER root

# Set the environment variable for your timezone if needed
# RUN apk add --no-cache tzdata
# ENV TZ=America/New_York

RUN npm install -g pnpm --force

USER node

# Installing contributed/custom extensions through npm on Railway
RUN pnpm install directus-extension-computed-interface && pnpm install directus-extension-upsert && \
pnpm install directus-extension-wpslug-interface && pnpm install pg && \
pnpm install directus-extension-flexible-editor && pnpm install @directus-labs/simple-list-interface && \
pnpm install @directus-labs/migration-bundle

# Migrations and Directus schema update
RUN npx directus bootstrap

# Restore schema snapshots
# COPY ./snapshots /directus/snapshots
# RUN npx directus schema apply --yes /directus/files/snapshots/snapshot.yaml