# Explicitly specify a Directus version to use on Railway
FROM directus/directus:11.1

USER root
RUN corepack enable

# Installing contributed/custom extensions through npm on Railway
RUN pnpm install directus-extension-computed-interface && pnpm install directus-extension-upsert && pnpm install directus-extension-wpslug-interface && pnpm install pg

USER node

# Migrations and Directus schema update
RUN npx directus bootstrap

# Restore schema snapshots
# COPY ./snapshots /directus/snapshots
# RUN npx directus schema apply --yes /directus/files/snapshots/snapshot.yaml